markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Alex Ray
url: http://machinaut.com
description: Circuit Hacking, Operating Systems, Motorcycles, Stuff
twitter: machinaut
github: machinaut
gravatar_url: http://gravatar.com/avatar/846948339f3f2809a07430997120c1e7
